# # Content
# excerpt_link: Read More

# Miscellaneous
rss:

# enter your weibo ID
weibo_show:  

github: https://github.com/lhy1024

scroll_spy: true

mathjax:
  enable: true
  cdn: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML